# Generated by Django 5.2.4 on 2025-07-19 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="price")),
                (
                    "description",
                    models.TextField(
                        db_column="description", verbose_name="description"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="price per night at the room in dollars",
                        max_digits=6,
                        verbose_name="price",
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="booking",
            name="hotel",
        ),
        migrations.AddField(
            model_name="booking",
            name="room",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="hotels.room"
            ),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Hotel",
        ),
    ]
