# Generated by Django 5.2.4 on 2025-07-19 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0002_room_remove_booking_hotel_booking_room_delete_hotel"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="title",
        ),
    ]
