# Generated by Django 5.2.4 on 2025-07-19 16:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0003_remove_room_title"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date of creation",
                verbose_name="date of creation",
            ),
        ),
    ]
