# Generated by Django 5.2.4 on 2025-07-27 14:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0004_room_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date of creation",
                verbose_name="date of creation",
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date of update",
                verbose_name="date of update",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                help_text="Date of update",
                verbose_name="date of update",
            ),
        ),
    ]
