# Generated by Django 5.2.4 on 2025-07-27 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotels", "0005_booking_created_at_booking_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date of creation",
                verbose_name="date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date of update", verbose_name="date of update"
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Date of creation",
                verbose_name="date of creation",
            ),
        ),
        migrations.AlterField(
            model_name="room",
            name="updated_at",
            field=models.DateTimeField(
                auto_now=True, help_text="Date of update", verbose_name="date of update"
            ),
        ),
    ]
