services:
 db:
   image: postgres:17
   container_name: booking_postgres
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5432:5432"
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - .env

 test-db:
   image: postgres:17
   container_name: booking_test_postgres
   environment:
     POSTGRES_DB: ${DATABASE_NAME}
     POSTGRES_USER: ${DATABASE_USERNAME}
     POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
   ports:
     - "5433:5432"
   volumes:
     - postgres_test_data:/var/lib/postgresql/data
   env_file:
     - .env.testing

 django-web:
   build: .
   volumes:
     - .:/app
   container_name: booking_django
   restart: unless-stopped
   ports:
     - "8000:8000"
   depends_on:
     - db
   environment:
     SECRET_KEY: ${SECRET_KEY}
     DEBUG: ${DEBUG}
     LOGLEVEL: ${LOGLEVEL}
     ALLOWED_HOSTS: ${ALLOWED_HOSTS}
     DATABASE_ENGINE: ${DATABASE_ENGINE}
     DATABASE_NAME: ${DATABASE_NAME}
     DATABASE_USERNAME: ${DATABASE_USERNAME}

     DATABASE_PASSWORD: ${DATABASE_PASSWORD}
     DATABASE_HOST: ${DATABASE_HOST}
     DATABASE_PORT: ${DATABASE_PORT}
   env_file:
     - .env

volumes:
   postgres_data:
   postgres_test_data:
